### ISSUE TITLE
Can't pass license key as a client option

### ISSUE THREAD

**Issue by cshehadi** [froala/yii2-froala-editor#5]
I'm possibly missing something, but I don't think I can pass the license key from the Yii2 widget to Froala.

```
froala\froalaeditor\FroalaEditorWidget::widget([
    'model' => $model,
    'attribute' => $attribute,
    'clientOptions'=> [
    'key' => 'my_key_goes_here',
   ],
]
```
If i add 'key' as one of the allowable params in FroalaEditorWidget.php on line 169, then it works.

Was it left out by design, or can it be included in future versions of this package?

**Comment by stefanneculai** [comment]
@dungphanxuan `key` option should have been included in https://github.com/froala/yii2-froala-editor/blob/master/FroalaEditorWidget.php#L94. Would it be possible to make a change to this so that any option can be passed to clientOption? There are users who might create their own plugins and want to add new options.

**Comment by dungphanxuan** [comment]
@cshehadi  thank you! fixed

**Comment by cshehadi** [comment]
thanks guys
